### ISSUE TITLE
Post periodic reminder to 'blogging' stream

### ISSUE THREAD

**Issue by sursh** [sursh/blaggregator#74]
Now that #67 is deployed, new folks to the blogging stream on Zulip won't know about the blaggregator.us site, and won't know how to add their own blogs. 

A periodic (perhaps monthly?) reminder to the stream about the site, how to add or edit their blogs, how to contribute, etc, might be useful for everyone. 

cc @punchagan

**Comment by punchagan** [comment]
The other option would be to have a link to Blaggregator with every post.  Something like `notifications powered by Blaggregator` or something.  A periodic reminder feels annoying, since it would show up as a new message in the stream. Additional text with each new post may also be annoying, but is easier to ignore.

**Comment by sursh** [comment]
Hmm....they both sound effective, which is least annoying? I'm not sure. Maybe we could do a quick Zulip poll?

**Comment by punchagan** [comment]
Yes, I guess asking the users is a good way to do it. :)

**Comment by sursh** [comment]
Here is the schedule of the upcoming batch start dates https://www.recurse.com/faq#start-date-question
